spring:
  application:
    name: authentication

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: auth

  datasource:
    url: jdbc:postgresql://localhost:5432/auth?currentSchema=auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: auth
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      # TODO: configure username and password in container
#      user: root
#      password:  root
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  kafka:
    bootstrap-servers: localhost:9092
    topics:
      new-user: user-created
      new-user-partition-num: 4
      edit-user: user-updated
      edit-user-partition-num: 4

application:
  jwt:
    access-expire-time-sec: 18000 # 5 hours
    refresh-expire-time-sec: 86400 # 1 day
    secret: f4dea871a7569cba13a3f56f0b4ea9a3

server:
  port: 8081